
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 19 15:59:17 GMT+08:00 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 26;
  public static final int LBRACKET = 42;
  public static final int CONST = 10;
  public static final int GE = 34;
  public static final int PERIOD = 41;
  public static final int ELSIF = 16;
  public static final int INTEGER = 2;
  public static final int LPAREN = 44;
  public static final int SEMI = 38;
  public static final int ARRAY = 8;
  public static final int MINUS = 24;
  public static final int WRITE = 5;
  public static final int RPAREN = 45;
  public static final int NOT = 37;
  public static final int AND = 36;
  public static final int LT = 31;
  public static final int RECORD = 7;
  public static final int TYPE = 11;
  public static final int OR = 35;
  public static final int COMMA = 40;
  public static final int BEGIN = 20;
  public static final int PLUS = 23;
  public static final int ASSIGN = 28;
  public static final int IF = 14;
  public static final int WRITELN = 6;
  public static final int LE = 32;
  public static final int OF = 22;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 43;
  public static final int error = 1;
  public static final int NUMBER = 47;
  public static final int MOD = 27;
  public static final int NEQ = 30;
  public static final int EQ = 29;
  public static final int MODULE = 9;
  public static final int TIMES = 25;
  public static final int COLON = 39;
  public static final int ELSE = 17;
  public static final int READ = 4;
  public static final int WHILE = 18;
  public static final int THEN = 15;
  public static final int END = 21;
  public static final int GT = 33;
  public static final int VAR = 12;
  public static final int PROCEDURE = 13;
  public static final int DO = 19;
  public static final int IDENTIFIER = 46;
}

