
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 20 12:25:31 GMT+08:00 2019
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 23;
  public static final int LBRACKET = 39;
  public static final int CONST = 7;
  public static final int GE = 31;
  public static final int PERIOD = 38;
  public static final int ELSIF = 13;
  public static final int INTEGER = 2;
  public static final int LPAREN = 41;
  public static final int SEMI = 35;
  public static final int ARRAY = 5;
  public static final int MINUS = 21;
  public static final int RPAREN = 42;
  public static final int NOT = 34;
  public static final int AND = 33;
  public static final int LT = 28;
  public static final int RECORD = 4;
  public static final int TYPE = 8;
  public static final int OR = 32;
  public static final int COMMA = 37;
  public static final int BEGIN = 17;
  public static final int PLUS = 20;
  public static final int ASSIGN = 25;
  public static final int IF = 11;
  public static final int LE = 29;
  public static final int OF = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 3;
  public static final int RBRACKET = 40;
  public static final int error = 1;
  public static final int NUMBER = 44;
  public static final int MOD = 24;
  public static final int NEQ = 27;
  public static final int EQ = 26;
  public static final int MODULE = 6;
  public static final int TIMES = 22;
  public static final int COLON = 36;
  public static final int ELSE = 14;
  public static final int WHILE = 15;
  public static final int THEN = 12;
  public static final int END = 18;
  public static final int GT = 30;
  public static final int VAR = 9;
  public static final int PROCEDURE = 10;
  public static final int DO = 16;
  public static final int IDENTIFIER = 43;
}

